#include "Engine.hpp"
#include "risk_models.pb.h" // Generated by CMake later

namespace RiskEngine {

    std::vector<double> Simulator::SimulateGBM(double S0, double r, double sigma, double T, int num_paths) {
        std::vector<double> paths(num_paths);
        std::mt19937 gen(42); // Fixed seed for reproducibility
        std::normal_distribution<> d(0, 1);

        double drift = (r - 0.5 * sigma * sigma) * T;
        double vol_sqrt_T = sigma * std::sqrt(T);

        for (int i = 0; i < num_paths; ++i) {
            double Z = d(gen);
            paths[i] = S0 * std::exp(drift + vol_sqrt_T * Z);
        }
        return paths;
    }

    void Pricer::CalculateRisk(const std::string& serialized_request, std::string& serialized_response) {
        // 1. Deserialize
        risk_models::TradeRequest request;
        if (!request.ParseFromString(serialized_request)) {
            throw std::runtime_error("Failed to parse Proto");
        }

        // 2. Simulate (Monte Carlo)
        int paths = 1000;
        auto final_spots = Simulator::SimulateGBM(
            request.spot_price(), request.risk_free_rate(),
            request.volatility(), request.maturity(), paths
        );

        // 3. Price (Payoff averaging)
        double total_payoff = 0.0;
        std::vector<double> payoffs;
        double discount = std::exp(-request.risk_free_rate() * request.maturity());

        for (double S_T : final_spots) {
            // Call Option Payoff: max(S - K, 0)
            double payoff = std::max(S_T - request.strike(), 0.0);
            payoffs.push_back(payoff * discount);
            total_payoff += payoff * discount;
        }

        double pv = total_payoff / paths;

        // 4. Calculate PFE (95th percentile of exposure)
        std::sort(payoffs.begin(), payoffs.end());
        double pfe = payoffs[(int)(0.95 * paths)];

        // 5. Serialize Response
        risk_models::ValuationResult result;
        result.set_trade_id(request.trade_id());
        result.set_counterparty_id(request.counterparty_id());
        result.set_present_value(pv);
        result.set_pfe_95(pfe);

        result.SerializeToString(&serialized_response);
    }
}